### ISSUE TITLE
Add a minio service 

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/mysql-docker#4]
It would be great to (optionally) include a minio service to allow S3-style storage.

**Comment by eywalker** [comment]
That’s best done as a separate container - the best practice for Docker is to make one container responsible for one service.

**Comment by dimitri-yatsenko** [comment]
But we use docker-compose to allow multiple services

**Comment by eywalker** [comment]
It'll be cleanest to have another repo for minio Docker build, and a different one that is about providing `docker-compose.yml` that'll launch all related services together. The `docker-compose.yml` here is provided strictly for quick testing and I wouldn't want to expand it with other services. The dedicated repo can refer to all relevant services (say including a service for Jupyter notebook server) and do so with image linkage rather than local build. Anyway, the purpose of this repository is to build and maintain mysql Docker container so I want to keep it clean and simple.

**Comment by guzman-raphael** [comment]
Closing as it is not appropriate for this repo to maintain `minio` images as well.
